@extends('layouts.app')

@section('title', $league->name.' | Amadara UNO')
@section('description', 'League results and competitors.')

@php
  $simulationInProgress = $league->simulations()->whereIn('status', [\App\Models\LeagueSimulation::PENDING, \App\Models\LeagueSimulation::RUNNING])->exists();
  $standings = $simulation?->standings->sortByDesc(fn ($standing) => [$standing->points, $standing->goal_difference, $standing->goals_for])->values() ?? collect();
  $winner = $standings->first();
  $winnerMember = $winner ? $league->users->firstWhere('id', $winner->user_id) : null;
  $winnerLogo = $winnerMember?->pivot?->team_logo_path ? \Illuminate\Support\Facades\Storage::url($winnerMember->pivot->team_logo_path) : null;
@endphp

@section('content')
<main class="mx-auto min-h-[calc(100vh-150px)] max-w-7xl px-5 py-10 lg:px-8 lg:py-14">
  <a href="{{ route('dashboard.index') }}" class="text-sm font-bold text-white/50 hover:text-uno-lime"><i class="bx bx-arrow-back mr-1"></i> Back to leagues</a>
  <div class="mt-6 flex flex-wrap items-end justify-between gap-5">
    <div><p class="text-xs font-extrabold uppercase tracking-[.22em] text-uno-lime">{{ $league->name }}</p><h1 class="mt-2 text-4xl font-bold tracking-[-.04em]">{{ $simulation ? 'League results.' : 'League table.' }}</h1><p class="mt-3 text-sm text-white/50">{{ $simulation ? 'The complete competition has been simulated.' : 'See who is ready and view every participant’s locked squad.' }}</p></div>
    <div class="flex flex-wrap items-center gap-3"><span class="rounded-full bg-white/10 px-4 py-2 text-xs font-extrabold uppercase tracking-wider text-white/70">{{ $simulationInProgress ? 'Simulation in progress' : ucfirst(str_replace('_', ' ', $league->status)) }}</span>@if (! $simulation && $league->owner_id === auth()->id() && $league->status === \App\Models\League::STATUS_YET_TO_START && ! $simulationInProgress && $league->readyUsers->count() === $league->users->count() && $league->users->isNotEmpty())<form method="POST" action="{{ route('leagues.start', $league) }}">@csrf<button type="submit" class="rounded-xl bg-uno-lime px-4 py-2 text-xs font-extrabold text-uno-navy hover:bg-white">Start league</button></form>@endif</div>
  </div>

  @if (! $simulation)
    <nav class="mt-8 flex gap-2 border-b border-white/10" aria-label="League sections"><a href="{{ route('leagues.show', $league) }}" class="rounded-t-xl border-b-2 border-uno-lime px-4 py-3 text-sm font-extrabold text-uno-lime">Table</a><a href="{{ route('squads.show', $league) }}" class="rounded-t-xl border-b-2 border-transparent px-4 py-3 text-sm font-bold text-white/50 hover:border-white/30 hover:text-white">My formation</a></nav>
    <section class="mt-6 overflow-hidden rounded-3xl border border-white/10 bg-white/[.03]"><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead class="bg-white/5 text-xs uppercase tracking-widest text-white/40"><tr><th class="px-5 py-4">Team</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Formation</th><th class="px-5 py-4 text-right">Squad</th></tr></thead><tbody class="divide-y divide-white/10">@foreach ($league->users as $member) @php $memberSquad = $league->squads->firstWhere('user_id', $member->id); @endphp<tr class="hover:bg-white/[.03]"><td class="px-5 py-4 font-bold">{{ $member->name }} @if ($member->id === $league->owner_id)<span class="ml-2 rounded-full bg-uno-lime/15 px-2 py-1 text-[10px] font-extrabold uppercase tracking-wide text-uno-lime">Owner</span>@endif</td><td class="px-5 py-4">@if ($member->pivot->ready_at)<span class="text-uno-lime"><i class="bx bx-check-circle mr-1"></i> Ready</span>@else<span class="text-white/40"><i class="bx bx-time-five mr-1"></i> Not ready</span>@endif</td><td class="px-5 py-4 text-white/60">{{ $memberSquad?->formation ?: 'No formation yet' }}</td><td class="px-5 py-4 text-right">@if ($memberSquad)<a href="{{ route('leagues.members.squad', [$league, $member]) }}" class="font-extrabold text-uno-lime hover:text-white">View squad <i class="bx bx-right-arrow-alt"></i></a>@else<span class="text-white/30">—</span>@endif</td></tr>@endforeach</tbody></table></div></section>
  @elseif ($simulationInProgress)
    <div class="mt-8 rounded-2xl border border-sky-300/20 bg-sky-300/10 px-5 py-4 text-sm text-sky-100"><i class="bx bx-loader-alt mr-2 animate-spin"></i> The league simulation is running. This page will update automatically when results are ready.</div>
    <script>
      (() => { const endpoint = @json(route('leagues.simulation.status', $league)); const resultsUrl = @json(route('leagues.show', $league)); let checking = false; const check = async () => { if (checking) return; checking = true; try { const response = await fetch(`${endpoint}?_=${Date.now()}`, { headers: { Accept: 'application/json' }, cache: 'no-store' }); const data = await response.json(); if (data.completed || data.failed) { window.location.assign(resultsUrl); return; } } catch (error) {} finally { checking = false; } }; check(); window.setInterval(check, 3000); })();
    </script>
  @else
    <section class="mt-8"><div class="flex items-end justify-between gap-4"><div><p class="text-xs font-extrabold uppercase tracking-[.2em] text-uno-lime">Competitors</p><h2 class="mt-2 text-2xl font-bold">The teams.</h2></div><span class="text-xs text-white/40">{{ $league->users->count() }} teams</span></div><div class="mt-5 flex max-w-full snap-x snap-mandatory overflow-x-auto px-5 py-5 pb-7 scrollbar-thin"><div class="flex items-center -space-x-5">@foreach ($league->users as $member) @php $teamSelections = $league->effectiveSelections->where('user_id', $member->id)->where('role', 'player'); $logo = $member->pivot->team_logo_path ? \Illuminate\Support\Facades\Storage::url($member->pivot->team_logo_path) : null; $modalId = 'team-modal-'.$member->id; @endphp<button type="button" data-team-open="{{ $modalId }}" class="relative grid h-20 w-20 shrink-0 snap-start place-items-center rounded-3xl border-4 border-[#031323] bg-uno-blue/30 text-3xl text-uno-lime shadow-xl transition hover:z-20 hover:scale-110 focus:z-20 focus:outline-none focus:ring-2 focus:ring-uno-lime">@if ($logo)<img src="{{ $logo }}" alt="{{ $member->name }} logo" class="h-full w-full rounded-[20px] object-cover">@else<i class="bx bx-shield"></i>@endif<span class="sr-only">View {{ $member->name }}</span></button><div id="{{ $modalId }}" data-team-modal class="fixed inset-0 z-50 hidden items-center justify-center bg-[#020b15]/80 px-4 backdrop-blur-sm"><div class="glass-panel max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-3xl p-6 shadow-uno"><div class="flex items-center justify-between gap-4"><div class="flex items-center gap-3">@if ($logo)<img src="{{ $logo }}" alt="" class="h-16 w-16 rounded-2xl object-cover">@else<span class="grid h-16 w-16 place-items-center rounded-2xl bg-uno-blue/20 text-2xl text-uno-lime"><i class="bx bx-shield"></i></span>@endif<div><p class="text-xs font-extrabold uppercase tracking-widest text-uno-lime">Team</p><h3 class="mt-1 text-2xl font-extrabold">{{ $member->name }}</h3></div></div><button type="button" data-team-close class="text-2xl text-white/45 hover:text-white" aria-label="Close"><i class="bx bx-x"></i></button></div><div class="mt-6 grid grid-cols-2 gap-2">@foreach ($teamSelections as $selection)<div class="rounded-xl bg-black/20 px-3 py-3 text-sm text-white/75"><span class="block truncate">{{ $selection->player_data['known_name'] ?? $selection->player_data['name'] }}</span><small class="text-[10px] uppercase text-white/35">{{ $selection->role }}</small></div>@endforeach</div><a href="{{ route('leagues.members.squad', [$league, $member]) }}" class="mt-5 inline-block text-xs font-extrabold text-uno-lime hover:text-white">View full squad <i class="bx bx-right-arrow-alt"></i></a></div></div>@endforeach</div></div></section>
    <script>
      document.querySelectorAll('[data-team-open]').forEach((button) => button.addEventListener('click', () => { const modal = document.getElementById(button.dataset.teamOpen); modal.classList.remove('hidden'); modal.classList.add('flex'); }));
      document.querySelectorAll('[data-team-close]').forEach((button) => button.addEventListener('click', () => { const modal = button.closest('[data-team-modal]'); modal.classList.add('hidden'); modal.classList.remove('flex'); }));
      document.querySelectorAll('[data-team-modal]').forEach((modal) => modal.addEventListener('click', (event) => { if (event.target === modal) { modal.classList.add('hidden'); modal.classList.remove('flex'); } }));
    </script>

    <section class="mt-12"><p class="text-xs font-extrabold uppercase tracking-[.2em] text-uno-lime">Matches results</p><h2 class="mt-2 text-2xl font-bold">Every fixture.</h2><div class="mt-4 grid gap-3">@foreach ($simulation->matches->sortBy('id')->values() as $index => $match)<details class="group rounded-2xl border border-white/10 bg-white/[.03]"><summary class="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3 p-5"><span class="text-xs font-extrabold uppercase tracking-widest text-white/35">Fixture {{ $index + 1 }}</span><span class="font-bold">{{ $match->homeUser->name }} <strong class="mx-2 text-uno-lime">{{ $match->home_score }} - {{ $match->away_score }}</strong> {{ $match->awayUser->name }}</span><span class="text-xs font-extrabold uppercase text-white/40">{{ str_replace('_', ' ', $match->result) }} <i class="bx bx-chevron-down ml-1 transition group-open:rotate-180"></i></span></summary><div class="border-t border-white/10 px-5 py-4">@if ($match->narrative)<p class="text-sm leading-6 text-white/60">{{ $match->narrative }}</p>@endif @if ($match->decisive_factors)<p class="mt-3 text-xs text-white/40"><span class="font-bold text-white/60">Decisive factors:</span> {{ collect($match->decisive_factors)->join(' · ') }}</p>@endif</div></details>@endforeach</div></section>

    @if ($winner && $winnerMember)<section class="relative mt-12 overflow-hidden rounded-[32px] border border-uno-lime/30 bg-gradient-to-br from-uno-lime/20 via-white/[.04] to-transparent px-6 py-12 text-center" data-winner><div class="pointer-events-none absolute inset-0 overflow-hidden" data-confetti aria-hidden="true"></div><p class="relative text-xs font-extrabold uppercase tracking-[.25em] text-uno-lime">Winner</p>@if ($winnerLogo)<img src="{{ $winnerLogo }}" alt="{{ $winnerMember->name }} logo" class="relative mx-auto mt-5 h-28 w-28 rounded-3xl object-cover shadow-2xl">@else<div class="relative mx-auto mt-5 grid h-28 w-28 place-items-center rounded-3xl bg-uno-blue/30 text-5xl text-uno-lime"><i class="bx bx-trophy"></i></div>@endif<h2 class="relative mt-5 text-3xl font-extrabold">{{ $winnerMember->name }}</h2><p class="relative mt-2 text-sm text-white/50">League champion · {{ $winner->points }} points</p></section>@endif

    <section class="mt-12"><p class="text-xs font-extrabold uppercase tracking-[.2em] text-uno-lime">Table</p><h2 class="mt-2 text-2xl font-bold">Final standings.</h2><div class="mt-4 overflow-x-auto rounded-3xl border border-white/10 bg-white/[.03]"><table class="w-full min-w-[650px] text-left text-sm"><thead class="bg-white/5 text-xs uppercase tracking-widest text-white/40"><tr><th class="px-5 py-4">#</th><th class="px-5 py-4">Team</th><th class="px-5 py-4">P</th><th class="px-5 py-4">W</th><th class="px-5 py-4">D</th><th class="px-5 py-4">L</th><th class="px-5 py-4">GD</th><th class="px-5 py-4">Pts</th></tr></thead><tbody class="divide-y divide-white/10">@foreach ($standings as $rank => $standing)<tr><td class="px-5 py-4 font-bold text-white/40">{{ $rank + 1 }}</td><td class="px-5 py-4 font-bold">{{ $standing->user->name }}</td><td class="px-5 py-4">{{ $standing->played }}</td><td class="px-5 py-4">{{ $standing->wins }}</td><td class="px-5 py-4">{{ $standing->draws }}</td><td class="px-5 py-4">{{ $standing->losses }}</td><td class="px-5 py-4">{{ $standing->goal_difference }}</td><td class="px-5 py-4 font-extrabold text-uno-lime">{{ $standing->points }}</td></tr>@endforeach</tbody></table></div></section>
    <script>
      document.querySelector('[data-winner]')?.querySelector('[data-confetti]') && (() => { const box = document.querySelector('[data-winner] [data-confetti]'); for (let i = 0; i < 70; i++) { const piece = document.createElement('i'); piece.style.left = `${Math.random() * 100}%`; piece.style.background = ['#d8ff5f', '#fff', '#55b8ff', '#ffcf5c'][i % 4]; piece.style.animationDelay = `${Math.random() * 1.5}s`; piece.style.transform = `rotate(${Math.random() * 360}deg)`; box.appendChild(piece); } })();
    </script>
  @endif
    @if ($simulation)
      <section class="mt-12"><p class="text-xs font-extrabold uppercase tracking-[.2em] text-uno-lime">Top scorers</p><h2 class="mt-2 text-2xl font-bold">Golden boot table.</h2><div class="mt-4 overflow-hidden rounded-3xl border border-white/10 bg-white/[.03]"><table class="w-full text-left text-sm"><thead class="bg-white/5 text-xs uppercase tracking-widest text-white/40"><tr><th class="px-5 py-4">#</th><th class="px-5 py-4">Player</th><th class="px-5 py-4">Team</th><th class="px-5 py-4 text-right">Goals</th></tr></thead><tbody class="divide-y divide-white/10">@foreach ($scorerTotals as $rank => $scorer)<tr><td class="px-5 py-4 font-bold text-white/40">{{ $rank + 1 }}</td><td class="px-5 py-4 font-bold">{{ $scorer['name'] }}</td><td class="px-5 py-4 text-white/60">{{ $scorer['team'] }}</td><td class="px-5 py-4 text-right text-lg font-extrabold text-uno-lime">{{ $scorer['goals'] }}</td></tr>@endforeach</tbody></table></div></section>
    @endif
</main>
<style>[data-confetti] i{position:absolute;top:-10%;width:8px;height:14px;animation:fall 3.5s linear infinite;opacity:.9}@keyframes fall{to{top:110%;transform:translateY(100vh) rotate(720deg)}}</style>
@endsection
